---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-demo-node-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: main/demo-node-app
    repoURL: https://github.com/VikashChoudahry/demo-k8s-manifest.git
    targetRevision: main
  syncPolicy:
    automated: {}
