---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  template:
    spec:
      containers:
        - name: flaskdemo
          resources:
            requests:
              cpu: 50m
              memory: 128Mi