---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node-app
spec:
  template:
    spec:
      containers:
        - name: demo-node-app
          resources:
            requests:
              cpu: 50m
              memory: 128Mi