---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo-service
  labels:
    app: flaskdemo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo