---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-node-app
  name: demo-node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-node-app
    spec:
      containers:
        - name: demo-node-app
          image: 303522029614.dkr.ecr.us-east-1.amazonaws.com/demo-node-app:build-0
status: {}