---
apiVersion: v1
kind: Service
metadata:
  name: demo-node-app-lb-service
  labels:
    app: demo-node-app-lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: demo-node-app